library("dplyr")
library("readr")
library("sf")
library("leaflet")
library("shiny")
library("sfarrow")
#library("mapdeck")
library("stringr")
library("tidyr")
#library("shinyMobile")
#library("qrcode")
library("hereR")
#library("rayshader")
library("purrr")

#mapdeck::set_token("pk.eyJ1IjoicmF0YWEiLCJhIjoiY2xleTlraHVvMDJxZDN0bDMzbHZqZmdueSJ9.pWvThW5XMznC9rLYwGV8Aw")
hereR::set_key("HAHdgL5_957xuemKdm9Gd4trBGZm1scz8SUDV4bSm0o")
